name = "shortengalls"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Enable KV namespace for URL storage
[[kv_namespaces]]
binding = "URLS"
id = "e1a22a86d5dd4260bd61cbb8805744e8"
